# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
    vmImage: 'ubuntu-latest'
    
variables:
   - name: dockerRegistryServiceConnection
     value: acrsampletesteu2
   - name: k8sNamespace
     value: rg-demo-sample-test-aks-samplenamespace
   - name: imagepullsecret
     value: employee-img-secret

stages:

- stage: Deploy
  displayName: Deploy stage

  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: 'conn-aks-lab'
              secretName: employee-img-secret
              namespace: lab1-namespace
              dockerRegistryEndpoint: conn-acr-lab
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: lab1-namespace
              kubernetesServiceConnection: 'conn-aks-lab'
              manifests: |
                $(Build.SourcesDirectory)/manifests/deployment.yml
              imagePullSecrets: |
                 $(imagePullSecret)
              # containers: |
              #    $(containerRegistry)/$(imageRepository):$(tag)

