apiVersion: v1
kind: Pod
metadata:
  name: employee-producer-pod
  labels: 
    app: employee-producer-label
    type: employee-data-service
spec:
  containers:
    - name: employee-producer-pod
      image: acr112.azurecr.io/employeeproducer:version1-buildimage
      ports:
      - containerPort: 8000
